### ISSUE TITLE
好几个环境下都无法自动播放下一曲

### ISSUE THREAD

**Issue by sxx1314** [shaonianzhentan/cloud_music#11]
ha环境：
docker版 105.5
python版108.x

首先是切换播放器比较难，都是一闪而过需要多点几次才能选中。
然后是播放一曲之后就不播放了，不管是dlna还是vlc。

log里会循环出现这个错误，一直循环不播放也会报。

```
2020-04-30 17:05:45 ERROR (SyncWorker_8) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_cloud_music/media_player.py", line 310, in interval
    if ':' in _media_position:
TypeError: argument of type 'int' is not iterable
```

一首播放完了自动停止之后重新点击下一首会出现如下报错，但是正常会播放。
```
2020-04-30 17:26:17 ERROR (MainThread) [homeassistant.helpers.service] Service async_media_stop for media_player.dlna_m_red incorrectly returns a coroutine object. Await result instead in service handler. Report bug to integration author.
2020-04-30 17:26:18 ERROR (MainThread) [homeassistant.helpers.service] Service async_play_media for media_player.dlna_m_red incorrectly returns a coroutine object. Await result instead in service handler. Report bug to integration author.

```

**Comment by sxx1314** [comment]
新版本可以播放下一首了 但是 依旧有 error信息
