### ISSUE TITLE
login是时候，res返回的是None？

### ISSUE THREAD

**Issue by hadrianl** [shaonianzhentan/cloud_music#15]
如题，还没深入排除问题
Error while setting up ha_cloud_music platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ha_cloud_music/media_player.py", line 125, in setup_platform
    loop.run_until_complete(mp.api_music.login())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/config/custom_components/ha_cloud_music/api_music.py", line 32, in login
    if res['code'] == 200:
TypeError: 'NoneType' object is not subscriptable

**Comment by hadrianl** [comment]
树莓派4b + hassio +  homeassistantv0.110.2
