### ISSUE TITLE
插件加载报错无法运行。。。。

### ISSUE THREAD

**Issue by plutosherry** [shaonianzhentan/cloud_music#25]
error.....错误信息如下：

`2020-10-03 01:33:04 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up ha_cloud_music platform for media_player

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)

  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)

  File "/config/custom_components/ha_cloud_music/media_player.py", line 65, in setup_platform
    api_config = ApiConfig(hass.config.path(".shaonianzhentan/ha_cloud_music"))

  File "/config/custom_components/ha_cloud_music/api_config.py", line 17, in __init__
    os.mkdir(_dir)

FileNotFoundError: [Errno 2] No such file or directory: '/config/.shaonianzhentan/ha_cloud_music'`

**Comment by shaonianzhentan** [comment]
估计应该是你使用的4.1版本，最新版已经修复了这个问题
