### ISSUE TITLE
升级到最新版homeassistant，音乐无法播放

### ISSUE THREAD

**Issue by singer1860** [shaonianzhentan/cloud_music#41]
播放音乐显示无法找到该首歌曲的链接，自动播放下一首。但是下一首依然无法播放

**Comment by singer1860** [comment]
Logger: homeassistant.core
Source: components/dlna_dmr/media_player.py:355 
First occurred: 下午2:24:54 (4 occurrences) 
Last logged: 下午2:27:22

Error executing service: <ServiceCall media_player.play_media (c:a297e496a32abc9f50c61e4b9774ab34): entity_id=['media_player.192_168_2_154_sonos_play_3'], extra=, media_type=music, media_id=http://music.163.com/song/media/outer/url?id=1804879213>
Error executing service: <ServiceCall media_player.play_media (c:0bb902e94341ea6949502d32b9b87acd): entity_id=['media_player.192_168_2_85_sonos_play_5'], extra=, media_type=music, media_id=http://music.163.com/song/media/outer/url?id=1804879213>
Error executing service: <ServiceCall media_player.play_media (c:8b77ffbd48ca5ccff053c4389b41ee72): entity_id=['media_player.192_168_2_85_sonos_play_5'], extra=, media_type=music, media_id=http://music.163.com/song/media/outer/url?id=519061704>
Error executing service: <ServiceCall media_player.play_media (c:0593330a2787a97ad520803c2eecae5b): entity_id=['media_player.192_168_2_154_sonos_play_3'], extra=, media_type=music, media_id=http://music.163.com/song/media/outer/url?id=519061704>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1471, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1490, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 595, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 632, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/dlna_dmr/media_player.py", line 105, in wrapper
    return await func(self, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/dlna_dmr/media_player.py", line 355, in async_play_media
    await self._device.async_set_transport_uri(
  File "/usr/local/lib/python3.8/site-packages/async_upnp_client/profiles/dlna.py", line 636, in async_set_transport_uri
    await action.async_call(InstanceID=0,
  File "/usr/local/lib/python3.8/site-packages/async_upnp_client/client.py", line 519, in async_call
    raise UpnpError('Error during async_call(), status: %s, body: %s' %
async_upnp_client.client.UpnpError: Error during async_call(), status: 500, body: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>714</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>
