### ISSUE TITLE
接口出现异常，请确定音乐接口服务是否正常运行

### ISSUE THREAD

**Issue by ilongjiang** [shaonianzhentan/cloud_music#55]
一直提示这个错误.但是音乐服务是正常得

**Comment by shaonianzhentan** [comment]
最好是能提供一下日志，这样方便排查问题

**Comment by ilongjiang** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/config/custom_components/ha_cloud_music/api_view.py", line 92, in post
    _result = await mp.api_music.search_music(_name)
  File "/config/custom_components/ha_cloud_music/api_music.py", line 173, in search_music
    if obj['code'] == 200:
TypeError: 'NoneType' object is not subscriptable

**Comment by ilongjiang** [comment]
Logger: aiohttp.server
Source: custom_components/ha_cloud_music/api_music.py:173
Integration: 云音乐 (documentation)
First occurred: 10:42:25 (1 occurrences)
Last logged: 10:42:25
Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
result = await result
File "/config/custom_components/ha_cloud_music/api_view.py", line 92, in post
_result = await mp.api_music.search_music(_name)
File "/config/custom_components/ha_cloud_music/api_music.py", line 173, in search_music
if obj['code'] == 200:
TypeError: 'NoneType' object is not subscriptable

**Comment by shaonianzhentan** [comment]
在搜索的时候出现了异常，你的接口是部署在哪里的？

**Comment by ilongjiang** [comment]
我是用群晖docker部署得。用您得早期版本一直没问题。就是最近升级这两个版本以后。登录也不能用了。后面到集成了登录这个版本也是不行。我重新部署了音乐服务还是不行。但是我打开接口部署得地址是对的。能访问。

**Comment by hanley520** [comment]
我也是这个问题

**Comment by shaonianzhentan** [comment]
> 我也是这个问题

这个问题我排查过，确实是网易的接口不稳定，建议升级接口服务到最新版
