### ISSUE TITLE
再报告个，感觉好像是tts的锅

### ISSUE THREAD

**Issue by doa2011** [shaonianzhentan/cloud_music#6]
日志如下：出现在调用tts服务自动播报开关状态之后，不是所有时候都会触发，不知道该如何解决
ps：这个tts服务感觉很不错。大佬可否帮忙判断下是啥原因啊？
2020-02-16 03:39:28 INFO (SyncWorker_7) [custom_components.dlna] dlna devices ['http://192.168.99.29:49153/description.xml']
2020-02-16 03:39:31 INFO (MainThread) [homeassistant.components.automation] Executing Door is Closed
2020-02-16 03:39:31 INFO (MainThread) [homeassistant.helpers.script] Script Door is Closed: Running script
2020-02-16 03:39:31 INFO (MainThread) [homeassistant.helpers.script] Script Door is Closed: Executing step call service
2020-02-16 03:39:41 INFO (MainThread) [homeassistant.helpers.script] Script Door is Closed: Executing step call service
2020-02-16 03:39:45 INFO (MainThread) [homeassistant.components.automation] Executing switch_status_tts
2020-02-16 03:39:45 INFO (MainThread) [homeassistant.helpers.script] Script switch_status_tts: Running script
2020-02-16 03:39:45 INFO (MainThread) [homeassistant.helpers.script] Script switch_status_tts: Executing step call service
2020-02-16 03:39:47 INFO (SyncWorker_12) [custom_components.ha_cloud_music.media_player] 【播放列表类型】：music
2020-02-16 03:39:47 INFO (SyncWorker_12) [custom_components.ha_cloud_music.media_player] 【当前播放音乐】【None】:【http://192.168.99.130:8123/api/tts_proxy/d8cecd22713bd01106aa1f52291be1fe550890c6_zh_15390481186305659454_baidu.mp3】
这是一个正常的错误： local variable 'music_info' referenced before assignment
2020-02-16 03:39:47 INFO (SyncWorker_12) [custom_components.ha_cloud_music.media_player] 【调用服务[media_player.192_168_99_29]】play_media：{'entity_id': 'media_player.192_168_99_29', 'media_content_id': 'http://192.168.99.130:8123/api/tts_proxy/d8cecd22713bd01106aa1f52291be1fe550890c6_zh_15390481186305659454_baidu.mp3', 'media_content_type': 'music'}
2020-02-16 03:39:48 ERROR (MainThread) [homeassistant.components.automation] Error while executing automation automation.door_is_closed. Unknown error for call_service at pos 2: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 431, in action
    await script_obj.async_run(variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 151, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 235, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 318, in _async_call_service
    context=context,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 98, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 165, in async_say_handle
    DOMAIN_MP, SERVICE_PLAY_MEDIA, data, blocking=True
  File "/usr/src/homeassistant/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 210, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 349, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 373, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/onkyo/media_player.py", line 385, in play_media
    source = self._reverse_mapping[self._current_source]
KeyError: None
2020-02-16 03:39:59 INFO (SyncWorker_9) [custom_components.dlna] dlna devices ['http://192.168.99.29:49153/description.xml']
------------------------------
然后就会出现homeassistant无法通过web访问的情况

**Comment by shaonianzhentan** [comment]
你是使用的外部的tts么?

这个插件有内置的tts服务，建议使用内置的，使用外部的tts服务会有莫名其妙的问题

**Comment by doa2011** [comment]
我配置了baidu的tts ，你意思是我在configuration 中直接去掉baidu的tts么？不配置任何其他tts ？

Monkey • D • Code <notifications@github.com> 于 2020年2月16日周日 下午4:47写道：

**Comment by shaonianzhentan** [comment]
我的意思是使用ha_cloud_music.tts这个服务，这是一个插件内置的tts服务，也是使用的百度的，这个是专门与播放器搭配使用的，TTS播放完了之后还能继续播放当前音乐，而不是TTS完了，当前音乐就暂停了

**Comment by doa2011** [comment]
我是用的这个，我女喜欢这个声音，能自动恢复音乐也很好。

Monkey • D • Code <notifications@github.com> 于 2020年2月17日周一 下午12:27写道：
