### ISSUE TITLE
树莓派srv+python3.7环境,会导致media_player平台无法加载

### ISSUE THREAD

**Issue by cctv838126** [shaonianzhentan/cloud_music#8]
Platform error: media_player
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config.py", line 762, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 232, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/srv/homeassistant/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/ha_cloud_music/media_player.py", line 28, in <module>
    from .api_tts import ApiTTS
  File "/home/homeassistant/.homeassistant/custom_components/ha_cloud_music/api_tts.py", line 2, in <module>
    from mutagen.mp3 import MP3
  File "/srv/homeassistant/lib/python3.7/site-packages/mutagen/mp3/__init__.py", line 17, in <module>
    from mutagen.id3 import ID3FileType, delete
  File "/srv/homeassistant/lib/python3.7/site-packages/mutagen/id3/__init__.py", line 33, in <module>
    from ._file import ID3, ID3FileType, delete, ID3v1SaveOptions
  File "/srv/homeassistant/lib/python3.7/site-packages/mutagen/id3/_file.py", line 20, in <module>
    from ._tags import ID3Tags, ID3Header, ID3SaveConfig
  File "/srv/homeassistant/lib/python3.7/site-packages/mutagen/id3/_tags.py", line 15, in <module>
    from mutagen._compat import PY3, itervalues, izip_longest
ImportError: cannot import name 'izip_longest' from 'mutagen._compat' (/srv/homeassistant/lib/python3.7/site-packages/mutagen/_compat.py)

**Comment by shaonianzhentan** [comment]
是这个依赖库mutagen导致的，你可能需要手动的安装它
